### ISSUE TITLE
Update README , put up the .env file content format

### ISSUE THREAD

**Issue by cpavnn** [cpavnn/salesforce-nightwatch.js#1]
### `.env` file is added to `gitignore`
* The file has to be present for the scripts to run, update the content format in README

**Comment by jordanhatcher** [comment]
Hello, I would like to work on this issue for Hacktoberfest. Is the only thing required to put the .env file format in the README, or does the whole README need updating? Could a .env.example file be added as a template instead?

**Comment by cpavnn** [comment]
Cool! `README` needs updation

Please add the following under `Prepare the scripts to run` Section in README
```
SALESFORCE_USERNAME = <YOUR-USERNAME>
SALESFORCE_PASSWORD = <YOUR-PASSWORD>
```

Thanks!
